name: techbot
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cookie_jar: ^4.0.9
  dio: ^5.9.1
  dio_cookie_manager: ^3.4.0
  equatable: ^2.0.8
  file_picker: ^11.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_pdfview: ^1.4.4
  flutter_secure_storage: ^10.0.0
  fluttertoast: ^9.0.0
  get_it: ^9.2.0
  go_router: ^17.1.0
  local_auth: ^3.0.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
